# General config
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y

# Enable ADC
CONFIG_ADC=y
CONFIG_ADC_ADS9224R=y

# Enable GPIO for DRDY pin
CONFIG_GPIO=y

# SPI is needed for communication with ADS9224R
CONFIG_SPI=y
